### ISSUE TITLE
Curl command not working

### ISSUE THREAD

**Issue by abhijitpa1992** [HellaVentures/Car-Diagnostic-API#2]
Hello,
I have tried your curl with my id and secret code. I am getting the below response.

<404 Not Found: Requested route ('a3b84f99-5529-45b3-be60-225668286daf.eu-gb.mybluemix.net') does not exist.>

Please let me know if the issue is generic or only from my side.

Thanks,
Abhijit

**Comment by ericmorfamorales** [comment]
Hi Abhijit,

in this curl command we used an API key with a limited amount of calls per day. In your case this maximum was probably reached. If you want to use this API in your own application, please sign up to Bluemix and use the service from there with your own API key.

Best regards,
Eric

**Comment by abhijitpa1992** [comment]
Hello Eric,

We have already registered with Bluemix service of IBM and we have been using this service of ibm bluemix catalog since last 6 months. Our Bluemix account has more than  1000 USD credit, but still we are getting this response since yesterday

<404 Not Found: Requested route ('a3b84f99-5529-45b3-be60-225668286daf.eu-gb.mybluemix.net') does not exist.>

CLIENT_ID = "e18bcb4e-c6c1-4d3b-b128-4f392c242c20”
CLIENT_SECRET = "K7uF2wJ5eX6fS1uL3eC6fB3vM1dA1pB8rH2tD7pE5aA4pN8sO1"
