### ISSUE TITLE
Can't find VIN

### ISSUE THREAD

**Issue by rbezemer** [HellaVentures/Car-Diagnostic-API#4]
2D8HN44E09R696932

This VIN couldn't be found by the api even though it's a valid VIN.

I'm actually curious about this service, what source are you using for vehicle DTC codes? We might be interested in using this for a mobile application if it has reasonable manufacturer specific error codes.

**Comment by ericmorfamorales** [comment]
The DTC codes that we use come from Hella Gutmann Solutions, so they are professionally maintained. Concerning the VIN number - our VIN decoder is not complete and doesn't cover all manufacturers.
